# https://alacritty.org/config-alacritty.html
# https://wiki.archlinux.org/title/Alacritty

[window]
opacity = 0.95
blur = true
# hyprland client selector is case sensitive
title = "alacritty"
class = { instance = "alacritty", general = "alacritty" }

[colors]
transparent_background_colors = true

[selection]
save_to_clipboard = true

[cursor]
style = { blinking = "On", shape = "Beam" }
vi_mode_style = { blinking = "On", shape = "Block" }
blink_timeout = 0
